[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"


[dependencies]
itertools = "0.10"

[[bin]]
name = "day_01"
path = "src/day_01.rs"


[[bin]]
name = "day_02"
path = "src/day_02.rs"